Sorting Algorithm/GnomeSort.js
Hi, I have added a sorting algorithm which is known as Gnome Sort.
It is written in javascript.
=> Gnome Sort

Searching Algorithm/Linear search.c
Added New File Linear search.c
=> Create Linear search.c

Sorting Algorithm/bucket_sort.py
bucket sort algorithm in python
=> bucket sort in python

Sorting Algorithm/SelectionSort.java
The java code performs selection sort and prints the elements after each sort to visualize the sorting.
=> SelectionSortJava

Searching Algorithm/Linear Search.py
Implementation of the linear search algorithm in Python.
Please review this PR and merge it.
=> Linear Search #6

Sorting Algorithm/HeapSort.cpp
Adding Heap Sort algorithm in C++ language.
=> Added HeapSort implementation in C++. Fixes #3

Graph algorithm/DFS_Algorithm.cpp
Depth First Seacrh traversal of a Graph in C++
=> Added DFS Algorithm in cpp

Sorting Algorithm/BubbleSort.cs
Added Bubble sort algorithm in C#. 
Issue: https://github.com/Bijay555/Hacktoberfest-Algorithms/issues/3.
=> Bubble sort csharp

Backtracking algorithm/N_Queen_Problem/README.md, Backtracking algorithm/N_Queen_Problem/n_queen.cpp
Problem:-
The n-queens puzzle is the problem of placing n queens on an n×n chessboard such that no two queens attack each other. Given an integer n, print all distinct solutions to the n-queens puzzle. Each solution contains distinct board configurations of the n-queens’ placement, where the solutions are a permutation of [1,2,3..n] in increasing order, here the number in the ith place denotes that the ith-column queen is placed in the row with that number.
This is a Backtracking Algorithm in c++ language. 
Fixed #1
=> Added the N queen Problem

Dynamic Programming/Mineditdistance.java
Created file: Java program to find minimum edit distance using dynamic programming
=> added file: Mineditdistance.java

Graph algorithm/Cycle_detection_undirected_graph.cpp, Trees algorithm/Morris Inorder and Preorder Traversals.cpp, Trees algorithm/MorrisTraversals.cpp
@Bijay555 My contribution for issue#33  and  issue#2 . Added Inorder and Preorder Morris Tree Traversals in cpp. Added cycle detection algorithm for undirected graphs in cpp.
=> Added Morris Tree Traversals and Cycle Detection Algorithms in cpp

Sorting Algorithm/BubbleSort.cpp
Added a Contribution to Sorting Algorithms
=> Added Bubble Sort in c++

Sorting Algorithm/CountingSort.java
Added java counting sort implementation for issue #3
=> Added java Counting sort #3 (hacktoberfest)

Sorting Algorithm/SelectionSort.cs
C# selection sort added to sorting algorithm folder
=> Added SelectionSort C#

Graph algorithm/BreadthFirstSearch.cs, Graph algorithm/DepthFirstSearch.cs
Adding DepthFirstSearch and BreadthFirstSearch in C# language. 
Request you to make it count towards Hacktoberfest if it follows the repository rules.
=> Add DFS and BFS in C# under Graph Algorithms

Trees algorithm/IsomorphicTrees.cpp
Added a new algorithm under the "trees algorithms" folder to find wheter two given trees are isomorphic or not.
=> Add: IsomorphicTrees

Sorting Algorithm/Merge_Sort_Algorithm/heapsort.java
Program to do heap sort using java
=>  heapsort.java

Sorting Algorithm/heapsort.py
Heap sort program using python
=> heapsort.py

Sorting Algorithm/RadixSort.java
#31 added radix sort under sorting algorithm folder.
=> Added radix sort

Sorting Algorithm/MergeSort_Recursively/mergeSort.java, Sorting Algorithm/QuickSort_Recursively/quickSort.java
Hey there @Bijay555 I have added two recursive programs of Quicksort and Mergesort
could you please review it
if you find them valuable then add this contribution of mine to your repo 😄
=> Added Recursive versions of Quick sort & Merge sort

Searching Algorithm/BinarySearch.cs
Code contains a full implementation of binary search, exuberant comments and a small test function that also compares my implementation to one that is built into List.
=> Implemented binary search in C#

Divide and Conquer Algorithms/maximumsubarraysum.c, Graph algorithm/prims.c, Greedy Algorithms/greedymaxsubarraysum.c, Sorting Algorithm/iterativebubblesort.c, Sorting Algorithm/iterativeinsertionsort.c, Sorting Algorithm/iterativeselectionsort.c, Sorting Algorithm/recursivebubblesort.c, Sorting Algorithm/recursiveinsertionsort.c, Sorting Algorithm/recursiveselectionsort.c
recursive and iterative implementations of selection sort, insertion sort, and bubble sort in C language
=> added iterative and recursive implementations of some sorting algos in C

Backtracking algorithm/KnightTourProblem.c
N*N board with the Knight placed on the first block of an empty board. Moving according to the rules of chess knight must visit each square exactly once. Print the order of each the cell in which they are visited.
=> KnightTourProblem.c

Dynamic Programming/fibonacci.py
Added Fibonacci Dynamic Programming
=> Added Fibonacci Dynamic Programming

Trees algorithm/BoundaryTraversal.cpp
Added Boundary Traversal of Binary Tree in C++. Happy Learning, Kudos to your work!
=> Boundary Traversal

Greedy Algorithms/dijkstra_greedy.py, Trees algorithm/red-black-tree.py
In computer science, a red–black tree is a kind of self-balancing binary search tree. Each node stores an extra bit representing color, used to ensure that the tree remains approximately balanced during insertions and deletions.
=> Red-Black-Tree with structure and operations

Searching Algorithm/Interpolation search .py
Added The Interpolation Search which is an improvement over Binary Search.
=> interpolation search.py

Searching Algorithm/Binary Search in Array.C
Binary Search in Array in C language
=> Create Binary Search in Array.C

Greedy Algorithms/WaterWalls.cs
Similar to this one: https://www.geeksforgeeks.org/trapping-rain-water/
=> Added WaterWalls algorithm

stack_using_linkedlist
Program for implementing stack using linkedList .
=> stack_using_linked List

Divide and Conquer Algorithms/Highest.java
I add program to decide what is the highest number
=> add Highest.java

Temperature Conversion using OOPs concept
=> Create Temperature Conversion using OOPs concept

Sorting Algorithm/RandQuickSort.java
Adding Randomized Quick Sort Algorithm in Java language.
=> Randomized Quick Sort 

Searching Algorithm/fibonaci_search.py
Added Fibonacci search as per issue #6 .
=> Added Python3 implementation of Fibonacci Search

Divide and Conquer Algorithms/binary_search_implementation.java, Dynamic Programming/FractionalKnapsackProblem.java
I hope this helps, contributing for the first time in open source for hacktoberfest. Thank you so much. Please do consider my contribution.
=> Added Fractional Knapsack Problem , binary_search_implementation

Greedy Algorithms/BoruvkaMST.cpp
Boruvka’s greedy algorithm as requested in #22 
Code written in C++.
=> Added the code for Boruvka's algorithm to find Minimum Spanning Tree

Dynamic Programming/Kadane_LargestSumContArray.cpp
Kadane_LargestSumContArray Using Dynamic Programming Algo
Programming Language Used: C++
=> Added Kandane problem

Graph algorithm/a_star.cpp
=> Added A* path search algorithm

Sorting Algorithm/InsertionSort.js
Added InsertionSort algorithm in javascript.
=> Added InsertionSort algorithm in javascript.

Trees algorithm/AVL Trees
AVL trees add delete operations
=> Create AVL Trees

Trees algorithm/Segment Tree
Segment add update and delete functionality
=> Create Segment Tree

Dynamic Programming/Longest Increasing Subsequence.java
Program to find the longest Increasing sub sequence
=> Length of  Longest Increasing Subsequence.java

Sorting Algorithm/MergeSort.js
Added MergeSort algorithm in javascript.
=> Added MergeSort algorithm in javascript.

Divide and Conquer Algorithms/binary_search.cpp
Hi. This is another binary search, but in C++ :smile:. I made recursive and non-recursive implementations.
=> Divide and Conquer Algorithms : Binary serach (two C++implementations)

Divide and Conquer Algorithms/k_order_statistics.cpp
Hi. This is not a recursive implementation of the k-order statistics search algorithm. The partition function selects a reference element using randomness.
=> Divide-and-conquer algorithm : Algorithm for finding k-th order statistics (random partition, С++)
